import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.scss';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
import Menu from '@/components/menu/menu';

import styles from './layout.module.scss';

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '600', '700'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <div className={styles.layout}>
          <Header />
          <div className={styles.main}>
            <div className={styles.menu}>
              <Menu />
            </div>
            <main>{children}</main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
